version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

### PHP-FPM ##############################################
  php-fpm:
    container_name: vanderson_blog_php
    build:
      context: ./.docker/php-fpm
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./.docker/php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    expose:
      - "9000"
    networks:
      - backend

### NGINX Server #########################################
  nginx:
    container_name: vanderson_blog_nginx
    build:
      context: ./.docker/nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

### MongoDB ##############################################
  mongo:
    container_name: vanderson_blog_mongodb
    build: ./.docker/mongo
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - backend

### MariaDB ##############################################
  mariadb:
    build:
      context: ./.docker/mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./.docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend
